# Generated by Django 4.2 on 2023-04-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationapp', '0002_accommodation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('category', models.CharField(max_length=30, null=True)),
                ('type', models.CharField(max_length=30, null=True)),
                ('amount', models.CharField(max_length=300, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
